# This is a basic workflow to help you get started with Actions

name: New feature branch application for ArgoCD on DEV

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:

env:
  REPOSITORY: sokube/simple-todo-list-infra.git

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  inform:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo "Branch $GITHUB_REF created, using account {{ github.actor }}""

    # Create a new remote branch in the infra repo
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://{{ github.actor }}:{{github.token}}@github.com/$REPOSITORY"
        source_branch: "dev"
        destination_repo: "https://{{ github.actor }}:{{github.token}}@github.com/$REPOSITORY"
        destination_branch: "test"

