# This is a basic workflow to help you get started with Actions

name: New feature branch application for ArgoCD on DEV

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:

env:
  REPOSITORY: sokube/simple-todo-list-infra.git
  FEATURE_BRANCH_NAME_PATTERN: "refs/heads/feature_(\K.*)"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  inform:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Runs a single command using the runners shell
    - name: Checks if feature branch
      run: |
      echo "Branch $GITHUB_REF created, using account ${{ github.actor }}""
      branch=$(echo "$GITHUB_REF" | grep -oP "$FEATURE_BRANCH_NAME_PATTERN")
      echo ::set-env name=FEATURE_BRANCH_NAME::"$branch"

    # Test
    - name: TEST
      if: ${{ env.FEATURE_BRANCH_NAME != ""}}
      run: |
      echo "This (${{ env.FEATURE_BRANCH_NAME }}) is a Feature branch !"

    # Create a new remote branch in the infra repo
    - name: repo-sync
      uses: wei/git-sync@v2
      if: ${{ env.FEATURE_BRANCH_NAME != ""}}
      with:
        source_repo: "https://${{ github.actor }}:${{ github.token }}@github.com/$REPOSITORY"
        source_branch: "dev"
        destination_repo: "https://${{ github.actor }}:${{ github.token }}@github.com/$REPOSITORY"
        destination_branch: "newfeature"

