# This is a basic workflow to help you get started with Actions

name: New feature branch application for ArgoCD on DEV

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  inform:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Branch $GITHUB_REF has been created

    # Create a new remote branch in the infra repo
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://{{ github.actor }}:{{github.token}}@github.com/sokube/simple-todo-list-infra"
        source_branch: "dev"
        destination_repo: "https://{{ github.actor }}:{{github.token}}@github.com/sokube/simple-todo-list-infra"
        destination_branch: "test"

  repo-sync:
    runs-on: ubuntu-latest
    steps:
